### ISSUE TITLE
Stopping an indefinite trigger

### ISSUE THREAD

**Issue by udif** [sgoadhouse/oscope-scpi#2]
I'm having issues with my USB-connected DSOX3034T where a poorly-defined trigger event leaves the scope waiting indefinitely for a trigger.
It seems that while it is waiting for the trigger, it no longer responds to SCPI commands.
Even sending a modeStop() doesn't help getting it out of the trigger.

I assume this doesn't happen with Ethernet or GPIB based interfaces, but I want to be sure it's a univeral thing and not an issue with my setup.

This is a huge issue for me because it means I cannot work remotely in a reliable way.
I also witnessed cases where the DSOX completely ignores USB input, even when it is not waiting for a trigger (and I can fully use the GUI), and even worse, there was a case when it simply lost its USB device (did not even appear in an `lsusb` scan).
In both cases the only solution was a manual power off/power on sequence.
The trigger issue on top is still the worst, because it is consistent, while those below were random and happened less frequently.

**Comment by sgoadhouse** [comment]
I have never seen my older MSOX3034A stop responding to SCPI commands. It does have an odd issue where getting a screen capture fails occasionally but I found a work around with `pycurl` to grab the image from the web GUI. Even when this happens, it still responds to SCPI commands.

It is possible that a particular SCPI command was issued, like making a measurement, and the oscilloscope waits for a trigger to be able to fulfill the request. However, I would expect some sort of timeout. 

Sounds like it may be worth you requesting support from Keysight since it may be a support issue.

**Comment by udif** [comment]
Yes, after some playing around with the triggers, the problem went away. I'm not sure what caused it in the first place.

**Comment by sgoadhouse** [comment]
Good news. Glad the problem went away.
